openapi: 3.0.3
info:
  title: Título
  description: |-
    descrição
  version: 1.0.0

tags:
  - name:
    description:


paths:
  /v1/auth/signup:
  /v1/auth/signin:
  /v1/account
  /v1/users/{username}:
